- Numpy(Numerical python) Math or number
- Pandas(Data frames)
- Matplotlib(TO draw graphs,visulation)
- For data analysis


## NumPy stands for Numerical Python.
- Numpy pakage used for mathamatical and scienctific computation.
- you can do linear algebra 
- NumPy’s main data structure is the multidimensional array.
- To create a vector, we simply create a 1-D array.


In [1]:
import numpy

In [ ]:
import cv2

In [5]:
!pip3 install opencv-python

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 90.3 MB 1.2 kB/s ta 0:00:012
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 18.1 MB 1.4 MB/s eta 0:00:01
  Created wheel for opencv-python: filename=opencv_python-4.6.0.66-cp39-cp39-macosx_10_14_x86_64.whl size=26347235 sha256=8c4897502f58cb84d783fdc12b3133a2be6cc2187ebda3579a2ff62357f604e6
  Stored in directory: /Users/sheelendersharma1/Library/Caches/pip/wheels/6c/3a/b0/162197b99d01e5d1a44096c7392a6bf8ae182a4ee9a85ef9af
Successfully built opencv-python
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.


# Numpy Array

In [ ]:
# matrix
# rows=2 and columns=3
#2*3
# [[1,2,3],[4,5,6]]

In [5]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
import numpy as np
print(np.__version__)

1.21.5


- numpy array
- numpy array is a kind of vectors
- (vectors means which as both negative and positive value) 
= ***axis0 means row, and axis1 means column***



In [7]:
# create a numpy array
import numpy as np
age=[10,20,30]
age_array=np.array(age)

age_array

array([10, 20, 30])

In [8]:
age

[10, 20, 30]

In [9]:
type(age_array)
# numpy n dimension array

numpy.ndarray

In [5]:
age_array.shape

(3,)

- shape >>> The shape of an array is the number of elements in each dimension.
- size  >>>>> In Python, numpy.size() function count the number of elements along a given axis.
- dtype(datatypes) >>>>> data type
- ndim(n-dimension) >>>> number of dimension.






In [10]:
age_array.shape

(3,)

In [11]:
age_array.size

3

In [12]:
age_array.dtype

dtype('int64')

In [13]:
age_array.ndim

1

In [14]:
# create array with some strings
n_array = np.array(["sri",4000,50.5555])
print(type(n_array))
print(n_array.size)
print(n_array.dtype)
print(n_array.ndim)
print(n_array.shape)

<class 'numpy.ndarray'>
3
<U32
1
(3,)


In [12]:
s_array = np.array([50.555,4444,555,666])
print(type(s_array))
print(s_array.size)
print(s_array.dtype)
print(s_array.ndim)
print(s_array.shape)

<class 'numpy.ndarray'>
4
float64
1
(4,)


In [15]:
arr1 = np.array([[1,2,3,4,5],[100,200,300,400,500]])
arr1

array([[  1,   2,   3,   4,   5],
       [100, 200, 300, 400, 500]])

In [16]:
arr1.shape

(2, 5)

In [15]:
arr1.size

10

In [17]:
arr1.ndim

2

In [18]:
arr1.dtype

dtype('int64')

In [18]:
type(arr1)

numpy.ndarray

In [20]:
arr2 =np.array([[1,2],[100,200,300]])

arr2

/var/folders/p6/z0mkbnv935lfj5knl3fvv_0m0000gp/T/ipykernel_732/3946091718.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 =np.array([[1,2],[100,200,300]])


array([list([1, 2]), list([100, 200, 300])], dtype=object)

In [21]:
arr2

array([list([1, 2]), list([100, 200, 300])], dtype=object)

In [22]:
arr2.ndim

1

In [28]:
# 3 D array

elm=[[[1,2,3],[100,200,300],[1000,2000,3000]]]
arr3=np.array(elm)

In [29]:
arr3

array([[[   1,    2,    3],
        [ 100,  200,  300],
        [1000, 2000, 3000]]])

In [30]:
arr3.shape
#(k,m,n)
# k= single list
#

(1, 3, 3)

In [31]:
arr3.size

9

In [32]:
arr3.ndim

3

In [38]:
ele2=[[1,2,3],[4,5,6]]
ele2[1]


[4, 5, 6]

In [46]:
ele=[[[1,2,3],[10,20,30]],[[1,2,3],[10,20,30]]]

a=np.array(ele)
print(a)

[[[ 1  2  3]
  [10 20 30]]

 [[ 1  2  3]
  [10 20 30]]]


In [43]:
a.ndim

3

In [44]:
a.shape

(2, 2, 3)

In [47]:
a.size

12

In [25]:
matrix=np.array([[1,2,3,4]
                 ,[5,6,7,8]])
matrix+100  

array([[101, 102, 103, 104],
       [105, 106, 107, 108]])

In [29]:
np.min(matrix,axis=0)

array([1, 2, 3, 4])

# random

In [48]:
import random

In [50]:
random.randint(1,10)

8

In [51]:
random.randint(0,1)

0

In [54]:
list1=[]
for i in range(5):
    list1.append(random.randint(0,1))
    
list1

[1, 1, 0, 0, 1]

In [56]:
r1=[]
for i in range(10):
    a=random.random()
    r1.append(a)
    
r1

[0.4197282286899121,
 0.22996451589025058,
 0.7499137009622234,
 0.5845114606767959,
 0.3663873989006571,
 0.33474805896942805,
 0.09782826556121482,
 0.8672572824026331,
 0.3724308321908293,
 0.9452568462795441]

In [ ]:
# numpy array of random number
# no need list
# no need loop
# random() method return numbers,between [0,1]
# half interval here 0 include and 1 is not include
# the required number of random number is passed through size.



In [57]:
np.random.random(size=10)

array([0.13271416, 0.42299423, 0.02181392, 0.23961415, 0.42748873,
       0.42012401, 0.33253625, 0.28942441, 0.81553256, 0.72999235])

In [58]:
arr1.shape

(2, 5)

In [ ]:
# i want to generate random numbers with given shape..
# (3,3) (2,3),(3,4)

# np.random.random ()

In [10]:
np.random.random(10)  # np.random.random(): between (0,1) where 0 is inclusive and 1 is exclusive..

array([0.40571218, 0.90652276, 0.26183184, 0.19399087, 0.72371476,
       0.68577415, 0.89427224, 0.85927081, 0.40153872, 0.40206215])

In [11]:
np.random.random(5) # size is given to it..

array([0.13152723, 0.18580855, 0.88530158, 0.66722298, 0.78435848])

# np.random.rand
- rand() method creates an array of random number with given shape
- And the random numbers generate betwwen (0,1)
- Both zero and one not included

In [59]:
np.random.rand(2,3)

array([[0.50743022, 0.32341398, 0.17547829],
       [0.34369124, 0.14017151, 0.51954076]])

In [60]:
np.random.rand(3,2,3)

array([[[0.67319921, 0.0783061 , 0.16325217],
        [0.18985023, 0.66175129, 0.91620895]],

       [[0.61336032, 0.87259848, 0.90158028],
        [0.93286283, 0.23797062, 0.92868621]],

       [[0.4241462 , 0.93841248, 0.43836563],
        [0.36068834, 0.3526463 , 0.41508449]]])

In [61]:
np.random.rand(1,2,3)

array([[[0.16676278, 0.5114716 , 0.13152047],
        [0.3156186 , 0.27692673, 0.70032267]]])

# Normal Distribution
- Bell curve

- 50% values on right side of mean
- 50% values on left side of mean
- for normal distribution..


In [ ]:
# if i want to get random numbers from noral distribution
# it has some negative values some pos.


# np.random.randn

In [62]:
np.random.randn(2,3)  # Rnadom numbers from Normal Distribution.

array([[ 0.78198882,  0.41826743, -0.50072598],
       [ 1.40250754,  0.61095827,  1.47573294]])

# np.random.randint

In [6]:
import numpy as np
import random
np.random.randint(2,10)

# returns random numbers between 2,20
# (2,10)
# here 2 is inclusive and 10 is exclusive

8

In [7]:
np.random.randint(2,10)  #shift+tab

5

In [8]:
# i want to get 10 integers between 20,100
# where 20 is inclusove and 100 is exclusive..

np.random.randint(20,100,10)

array([98, 76, 45, 43, 68, 85, 74, 37, 92, 79])

- np.random.random(): between (0,1) where 0 is inclusive and 1 is exclusive..
- np.random.rand(): Give the random number to the given shape..
- np.random.randn(): Rnadom numbers from Normal Distribution.
- np.random.randint(): Random number betwwen given range of integers..
    

**np.arange**

In [ ]:
- np.arange() also used to create numpy array
- The numbers generated with some difference.


In [15]:
for i in range(1,10,2):
    print(i) 

1
3
5
7
9


In [18]:
# using arange lib..
even=np.arange(1,20,2,float) # also write this>>  np.arange(start=1,stop=20,step=2,dtype=float)
print(even)
print(type(even))

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
<class 'numpy.ndarray'>


In [9]:
odd=np.arange(1,20,3,int)
print(odd)
print(type(odd))
print(odd.dtype)
print(odd.size)
print(odd.shape)
print(odd.ndim)

[ 1  4  7 10 13 16 19]
<class 'numpy.ndarray'>
int64
7
(7,)
1


**Pattern**

# np.linspace 

- It is like a scale
- It will generate only specified numbers in a specific range
- Range (start,stop)
- How many numbers i need to display (num)

In [19]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [10]:
np.linspace(1,100,4)

array([  1.,  34.,  67., 100.])

In [16]:
np.linspace(1,100,6)


array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [ ]:
# suppose if you want to make all zeros..
# suppose if you want to make all ones..


In [20]:
np.zeros(10)
# 1D

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# shape

np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**np.empty**

- generates a random matrix with given shape and give data type

In [25]:
np.empty(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.empty(shape=(3,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
np.empty(shape=(3,3),dtype='float')

array([[ 0.00000000e+000, -1.49457615e-154,  4.63461863e+228],
       [ 2.62159492e-258,  6.01347002e-154,  4.82191851e+233],
       [ 3.51527682e+257,  6.80085840e+199,  6.01346953e-154]])

**np.full**

- np.full also returns the matrix with some full value

In [33]:
np.full((3,3),fill_value=100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

**np.identity**

In [34]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# np.eye

In [ ]:
# N*M matrix
# 4*5 matrix
# 

In [35]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [36]:
np.eye(4,5,k=0)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [37]:
np.eye(4,5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.eye(4,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.eye(4,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.eye(4,5,k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [41]:
np.random.random(): between (0,1) where 0 is inclusive and 1 is exclusive..
np.random.rand(): Give the random number to the given shape..
np.random.randn(): Rnadom numbers from Normal Distribution.
np.random.randint(): Random number betwwen given range of integers..
np.arange()
np.linspace()
np.empty()
np.null()
np.identity()
np.eye()

SyntaxError: illegal target for annotation (1691897766.py, line 1)

## Reshape

In [ ]:
# numpy array has shape(3,2)
# reshape array into (6,1)


In [42]:
employee=np.array([('Ram',18),
                   ('Laxman',20),
                   ('Krishan',22)])

In [43]:
employee

array([['Ram', '18'],
       ['Laxman', '20'],
       ['Krishan', '22']], dtype='<U21')

In [44]:
employee.shape

(3, 2)

In [45]:
employee_reshaped_61=employee.reshape(6,1)

In [46]:
employee_reshaped_61

array([['Ram'],
       ['18'],
       ['Laxman'],
       ['20'],
       ['Krishan'],
       ['22']], dtype='<U21')

In [48]:
employee_reshaped_16=employee.reshape(1,6)
employee_reshaped_16
# 1 row 6 columns
# In a main list one list is there in that 6 elements are there

array([['Ram', '18', 'Laxman', '20', 'Krishan', '22']], dtype='<U21')

In [50]:
employee_reshaped_23=employee.reshape(2,3)
employee_reshaped_23
# 2 rows 3 colums
# in main list 2 lists are there,in each list 3 elements are there

array([['Ram', '18', 'Laxman'],
       ['20', 'Krishan', '22']], dtype='<U21')

In [51]:
employee_reshaped_33=employee.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [55]:
employee

array([['Ram', '18'],
       ['Laxman', '20'],
       ['Krishan', '22']], dtype='<U21')

In [53]:
employee[1][0]

'Laxman'

In [54]:
employee[0][1]

'18'

** slicing **

In [60]:
arr1=np.array([73,78,65,33.3,92,45,'A'])
arr1

array(['73', '78', '65', '33.3', '92', '45', 'A'], dtype='<U32')

In [57]:
arr1[3:5]

array([33.3, 92. ])

In [58]:
arr1[3:]

array([33.3, 92. , 45. ])

In [59]:
arr1[0:3]

array([73., 78., 65.])

In [61]:
# 2-D array

arr2=np.array([(73,45,67),(21,36,19)])
arr2

array([[73, 45, 67],
       [21, 36, 19]])

In [68]:
# square data or rectangle 
# colums rows
# axis =0-----row
# axis=1---column


array([[73, 45, 67],
       [21, 36, 19]])

In [69]:
arr2[0:,0:1]

array([[73],
       [21]])

In [72]:
arr2[0:2,0:2]

array([[73, 45],
       [21, 36]])

In [73]:
arr2[:,1:]

array([[45, 67],
       [36, 19]])

## Array operations

In [79]:
odd_num=np.array([1,3,5,7,9])
even_num=np.array([2,4,6,8,10])
print("sum:",odd_num+even_num)
print("sub:",odd_num-even_num)
print("mul:",odd_num*even_num)
print("division:",odd_num/even_num)

sum: [ 3  7 11 15 19]
sub: [-1 -1 -1 -1 -1]
mul: [ 2 12 30 56 90]
division: [0.5        0.75       0.83333333 0.875      0.9       ]


In [76]:
list1=[1,3,5,7,9]
list2=[2,4,6,9,10]

for i,j in zip(list1,list2):
    print(i+j)

3
7
11
16
19


In [81]:
ary=np.array([[1,2,3],[0,1,4]])
print(ary.size)

6


In [83]:
a=np.array([1,2,3,4,5],ndmin=2)
print(a)

[[1 2 3 4 5]]


In [84]:
ary=np.array([1,2,3,5,8])
ary= ary+1
print(ary[1])

3


In [1]:
import numpy as np
np.array(list)

array(<class 'list'>, dtype=object)

In [2]:
list1=[1,2,3]
list2=[1,2,3]

list1+list2

[1, 2, 3, 1, 2, 3]

In [5]:
list1*list2

TypeError: can't multiply sequence by non-int of type 'list'

In [3]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [4]:
arr1*2

array([2, 4, 6])

## Matrix Multiplication

In [6]:
m1=np.array([[1,0,2],
            [4,-2,3]])
m2=np.array([[4,0,1],
            [2,3,0]])



In [7]:
m1.shape

(2, 3)

In [8]:
m2.shape

(2, 3)

In [9]:
m1*m2
# element wise product
# Hadmard product

array([[ 4,  0,  2],
       [ 8, -6,  0]])

In [10]:
m1=np.array([[1,0,2],
            [4,-2,3]])
m2=np.array([[4,0],[2,3],[1,4]])

In [11]:
m1.shape

(2, 3)

In [12]:
m2.shape

(3, 2)

In [13]:
m1.dot(m2)

array([[ 6,  8],
       [15,  6]])

**np.square**
- to return square of the elements


In [18]:
arr1=np.array([10,20,30,40])
arr2=np.square(arr1)

In [19]:
arr2

array([ 100,  400,  900, 1600])

In [20]:
np.sqrt(arr2)
# for sruqre root

array([10., 20., 30., 40.])

**np.power**

In [21]:
np.power(arr1,2)

array([ 100,  400,  900, 1600])

In [22]:
np.power(arr1,3)

array([ 1000,  8000, 27000, 64000])

**np.transpose**

In [24]:
m1.shape

(2, 3)

In [26]:
m1_t=np.transpose(m1)
m1_t

array([[ 1,  4],
       [ 0, -2],
       [ 2,  3]])

In [27]:
list1

[1, 2, 3]

In [28]:
list2

[1, 2, 3]

In [30]:
list1+list2 # concatentation

[1, 2, 3, 1, 2, 3]

In [39]:
arr1

array([10, 20, 30, 40])

In [40]:
arr2

array([ 100,  400,  900, 1600])

In [37]:
arr1+arr2 # addition

array([ 110,  420,  930, 1640])

**np.concatenate**

In [44]:
# 1-D concatetiona

new_array=np.concatenate([arr1,arr2])
new_array

array([  10,   20,   30,   40,  100,  400,  900, 1600])

In [45]:
names=np.array([['A',1],['B',2],['C',3]])
city=np.array([['Hyd','040'],['Bengaluru','080'],['chennai','044']])

In [46]:
names

array([['A', '1'],
       ['B', '2'],
       ['C', '3']], dtype='<U21')

In [47]:
city

array([['Hyd', '040'],
       ['Bengaluru', '080'],
       ['chennai', '044']], dtype='<U9')

In [48]:
np.concatenate([names,city])

array([['A', '1'],
       ['B', '2'],
       ['C', '3'],
       ['Hyd', '040'],
       ['Bengaluru', '080'],
       ['chennai', '044']], dtype='<U21')

In [49]:
np.concatenate([names,city],axis=0) # rows

array([['A', '1'],
       ['B', '2'],
       ['C', '3'],
       ['Hyd', '040'],
       ['Bengaluru', '080'],
       ['chennai', '044']], dtype='<U21')

In [50]:
np.concatenate([names,city],axis=1) # column

array([['A', '1', 'Hyd', '040'],
       ['B', '2', 'Bengaluru', '080'],
       ['C', '3', 'chennai', '044']], dtype='<U21')

**np.flatten**
- Any shape of array converts into single dimession

In [51]:
names

array([['A', '1'],
       ['B', '2'],
       ['C', '3']], dtype='<U21')

In [52]:
np.ndarray.flatten(names)
# 1-D

array(['A', '1', 'B', '2', 'C', '3'], dtype='<U21')

## iteration

In [53]:
arr_name=np.ndarray.flatten(names)

In [54]:
arr_name

array(['A', '1', 'B', '2', 'C', '3'], dtype='<U21')

In [55]:
list1=[i for i in arr_name]
list1
# iterating array elements using for loop

['A', '1', 'B', '2', 'C', '3']

In [56]:
arr_name.tolist() # convert array into list

['A', '1', 'B', '2', 'C', '3']

In [57]:
names

array([['A', '1'],
       ['B', '2'],
       ['C', '3']], dtype='<U21')

In [58]:
for i in names:
    for j in i:
        print(j)

A
1
B
2
C
3


# Numpy operation take less time 

In [59]:
import time
size=1000000
# crate a list
list1=range(size) #[0,1,2,...........1000000]
list2=range(size) # [0,1,2,3.......10000000]

start_time=time.time()
list3=[(a+b) for a,b in zip(list1,list2)]
end_time=time.time()
print("Time taken in seconds:",(end_time-start_time))

Time taken in seconds: 0.15759491920471191


In [60]:
import time
size=1000000
# crate a list
aar1=np.arange(size) #[0,1,2,...........1000000]
aar2=np.arange(size)# [0,1,2,3.......10000000]

start_time=time.time()
arr3=aar1+aar2
end_time=time.time()
print("Time taken in seconds:",(end_time-start_time))

Time taken in seconds: 0.0061798095703125
