In [5]:
Write a NumPy program to replace the negative values in a NumPy array with 0.

Write a NumPy program to replace all elements of a NumPy array that are greater than the specified array.[Expected Output:
Original array:
[[ 0.42436315 0.48558583 0.32924763]
[ 0.7439979 0.58220701 0.38213418]
[ 0.5097581 0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than. 5
[[ 0.42436315 0.48558583 0.32924763]
[ 0.5 0.5 0.38213418]
[ 0.5 0.34528799 0.1563123 ]]]


Write a NumPy program to convert a NumPy array into Python list structure.


Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).


Write a NumPy program to convert 1-D arrays as columns into a 2-D array.Sample array: (10,20,30), (40,50,60)
    
Write a NumPy program to concatenate two 2-dimensional arrays.
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
                
                
Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.
                
Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order.[Expected Output:
(3, 4, 2)
(4, 2, 3)]
                
                
Write a NumPy program to view inputs as arrays with at least two dimensions, three dimensions.


Write a NumPy program to create a 4x4 array, now create a new array from the said array swapping first and last, second and third columns.       
                
Write a NumPy program to multiply two given arrays of the same size element-by-element.

Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
                
Write a NumPy program to create a 3x3 identity matrix.
                
Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.
                
Write a NumPy program to get help on the add function.
                

                

                

                
                
    
    
    



SyntaxError: invalid syntax (1995638567.py, line 1)

In [76]:
# Write a NumPy program to replace the negative values in a NumPy array with 0.


import numpy as np
arr=np.array([1,-1,2,-2,3,-3,0,4,-4,5,-5])
print(arr)
arr[arr<0]=0
print(arr)

[ 1 -1  2 -2  3 -3  0  4 -4  5 -5]
[1 0 2 0 3 0 0 4 0 5 0]


In [77]:
# 2nd method

arr1=np.array(range(-10,10,2))
print(arr1)
arr1[arr1<0]=0
print(arr1)


[-10  -8  -6  -4  -2   0   2   4   6   8]
[0 0 0 0 0 0 2 4 6 8]


Write a NumPy program to replace all elements of a NumPy array that are greater than the specified array.[Expected Output:
Original array:
[[ 0.42436315 0.48558583 0.32924763]
[ 0.7439979 0.58220701 0.38213418]
[ 0.5097581 0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than. 5
[[ 0.42436315 0.48558583 0.32924763]
[ 0.5 0.5 0.38213418]
[ 0.5 0.34528799 0.1563123 ]]]

In [78]:
original_array=np.array([[ 0.42436315,0.48558583,0.32924763],
                         [ 0.7439979,0.58220701,0.38213418],
                         [ 0.5097581,0.34528799,0.1563123 ]])
print("Original array:",'\n',original_array)
original_array[original_array>0.5]=0.5
original_array

Original array: 
 [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]


array([[0.42436315, 0.48558583, 0.32924763],
       [0.5       , 0.5       , 0.38213418],
       [0.5       , 0.34528799, 0.1563123 ]])

In [79]:
#Write a NumPy program to convert a NumPy array into Python list structure.
from numpy import random
numpy_arr=np.array(random.rand(6,2))
print("numpy array:","\n",numpy_arr)

list_str=numpy_arr.tolist()
print("list structure:","\n",list_str)
type(list_str)

numpy array: 
 [[0.36824154 0.95715516]
 [0.14035078 0.87008726]
 [0.47360805 0.80091075]
 [0.52047748 0.67887953]
 [0.72063265 0.58201979]
 [0.53737323 0.75861562]]
list structure: 
 [[0.36824153984054797, 0.9571551589530464], [0.14035078041264515, 0.8700872583584364], [0.4736080452737105, 0.8009107519796442], [0.5204774795512048, 0.6788795301189603], [0.7206326547259168, 0.5820197920751071], [0.5373732294490107, 0.7586156243223572]]


list

In [80]:

# Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

number=range(0,10)
num=np.array(suff_number)
print("numpy array:",'\n',num)
random.shuffle(num)
print("shuffle number:",'\n',num)


numpy array: 
 [0 1 2 3 4 5 6 7 8 9]
shuffle number: 
 [1 9 0 5 2 8 6 3 7 4]


In [91]:
#Write a NumPy program to convert 1-D arrays as columns into a 2-D array.Sample array: (10,20,30), (40,50,60)
arr_1d=np.array([[10,20,30],[40,50,60]])
print(arr_1d.ndim)
print(arr_1d.shape)
print(arr_1d.reshape(3,2))



2
(2, 3)
[[10 20]
 [30 40]
 [50 60]]
(2, 3)


In [99]:
#Write a NumPy program to concatenate two 2-dimensional arrays.
#Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]


array1=np.array([[0, 1, 3],[5, 7, 9]])
array2=np.array([[0, 2, 4],[6, 8, 10]])
con=np.concatenate([array1,array2]) 
con

array([[ 0,  1,  3],
       [ 5,  7,  9],
       [ 0,  2,  4],
       [ 6,  8, 10]])

In [127]:
#Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4
matrix=np.arange(5)
print(matrix)
mat2=np.tile(matrix,(5,1))
mat2

[0 1 2 3 4]


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
# Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order.
# [Expected Output:
# (3, 4, 2)
# (4, 2, 3)]

num=np.array([3,4,2])
